[2024-06-05T09:40:45.067+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert_3.detect_and_alert scheduled__2024-06-04T17:00:00+00:00 [queued]>
[2024-06-05T09:40:45.088+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert_3.detect_and_alert scheduled__2024-06-04T17:00:00+00:00 [queued]>
[2024-06-05T09:40:45.090+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-05T09:40:45.188+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): detect_and_alert> on 2024-06-04 17:00:00+00:00
[2024-06-05T09:40:45.204+0000] {standard_task_runner.py:60} INFO - Started process 23121 to run task
[2024-06-05T09:40:45.214+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'alert_3', 'detect_and_alert', 'scheduled__2024-06-04T17:00:00+00:00', '--job-id', '1156', '--raw', '--subdir', 'DAGS_FOLDER/alert_3.py', '--cfg-path', '/tmp/tmp96r6iolm']
[2024-06-05T09:40:45.219+0000] {standard_task_runner.py:88} INFO - Job 1156: Subtask detect_and_alert
[2024-06-05T09:40:45.331+0000] {task_command.py:423} INFO - Running <TaskInstance: alert_3.detect_and_alert scheduled__2024-06-04T17:00:00+00:00 [running]> on host e98391521b34
[2024-06-05T09:40:46.021+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alert_3' AIRFLOW_CTX_TASK_ID='detect_and_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T17:00:00+00:00'
[2024-06-05T09:40:58.948+0000] {logging_mixin.py:188} INFO - Traceback (most recent call last):
  File "/opt/***/dags/network_model/anomaly_test.py", line 26, in <module>
    model = joblib.load('isolation_forest_model.pkl')
  File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'isolation_forest_model.pkl'
[2024-06-05T09:40:59.852+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-05T09:41:00.007+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=alert_3, task_id=detect_and_alert, execution_date=20240604T170000, start_date=20240605T094045, end_date=20240605T094100
[2024-06-05T09:41:00.425+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-05T09:41:01.325+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
