[2024-05-20T02:07:46.494+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509
[2024-05-20T02:07:46.495+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs'
[2024-05-20T02:07:46.535+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509
[2024-05-20T02:07:46.537+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs'
[2024-05-20T02:07:46.573+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_assignment.todos_to_gcs manual__2024-05-20T02:07:11.419274+00:00 [queued]>
[2024-05-20T02:07:46.591+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_assignment.todos_to_gcs manual__2024-05-20T02:07:11.419274+00:00 [queued]>
[2024-05-20T02:07:46.592+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-20T02:07:46.615+0000] {taskinstance.py:2191} INFO - Executing <Task(LocalFilesystemToGCSOperator): todos_to_gcs> on 2024-05-20 02:07:11.419274+00:00
[2024-05-20T02:07:46.628+0000] {standard_task_runner.py:60} INFO - Started process 1425 to run task
[2024-05-20T02:07:46.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_assignment', 'todos_to_gcs', 'manual__2024-05-20T02:07:11.419274+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weekly_assignment.py', '--cfg-path', '/tmp/tmp8ihfxatf']
[2024-05-20T02:07:46.634+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask todos_to_gcs
[2024-05-20T02:07:46.699+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509
[2024-05-20T02:07:46.701+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=weekly_assignment/run_id=manual__2024-05-20T02:07:11.419274+00:00/task_id=todos_to_gcs'
[2024-05-20T02:07:46.706+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_assignment.todos_to_gcs manual__2024-05-20T02:07:11.419274+00:00 [running]> on host 3e756f125b35
[2024-05-20T02:07:46.821+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_assignment' AIRFLOW_CTX_TASK_ID='todos_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T02:07:11.419274+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T02:07:11.419274+00:00'
[2024-05-20T02:07:46.849+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 90, in execute
    hook = GCSHook(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 157, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 242, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2024-05-20T02:07:46.856+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weekly_assignment, task_id=todos_to_gcs, execution_date=20240520T020711, start_date=20240520T020746, end_date=20240520T020746
[2024-05-20T02:07:46.879+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task todos_to_gcs (The conn_id `google_cloud_default` isn't defined; 1425)
[2024-05-20T02:07:46.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-20T02:07:46.952+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
