[2024-05-29T14:25:55.548+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dbt.run_dbt_model manual__2024-05-29T14:20:49.349773+00:00 [queued]>
[2024-05-29T14:25:55.566+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dbt.run_dbt_model manual__2024-05-29T14:20:49.349773+00:00 [queued]>
[2024-05-29T14:25:55.566+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-05-29T14:25:55.594+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_model> on 2024-05-29 14:20:49.349773+00:00
[2024-05-29T14:25:55.604+0000] {standard_task_runner.py:60} INFO - Started process 7407 to run task
[2024-05-29T14:25:55.608+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'trigger_dbt', 'run_dbt_model', 'manual__2024-05-29T14:20:49.349773+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dbt.py', '--cfg-path', '/tmp/tmpnd5dw29j']
[2024-05-29T14:25:55.611+0000] {standard_task_runner.py:88} INFO - Job 368: Subtask run_dbt_model
[2024-05-29T14:25:55.667+0000] {task_command.py:423} INFO - Running <TaskInstance: trigger_dbt.run_dbt_model manual__2024-05-29T14:20:49.349773+00:00 [running]> on host be0574dd2df3
[2024-05-29T14:25:55.830+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T14:20:49.349773+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T14:20:49.349773+00:00'
[2024-05-29T14:25:55.834+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-29T14:25:55.855+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'powershell -Command "cd C:/learn-dbt/learndbt; dbt run --models clean_network"']
[2024-05-29T14:25:55.890+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T14:25:55.914+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: powershell: command not found
[2024-05-29T14:25:55.915+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-29T14:25:55.936+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-29T14:25:55.948+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=trigger_dbt, task_id=run_dbt_model, execution_date=20240529T142049, start_date=20240529T142555, end_date=20240529T142555
[2024-05-29T14:25:56.024+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 368 for task run_dbt_model (Bash command failed. The command returned a non-zero exit code 127.; 7407)
[2024-05-29T14:25:56.065+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-29T14:25:56.109+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
