[2024-06-07T03:40:07.595+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: alert_combine.detect_and_alert scheduled__2024-06-06T15:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
