[2024-06-05T09:37:14.733+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: alert_3.detect_and_alert scheduled__2024-06-04T11:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
